# Generated by Django 4.2.3 on 2023-11-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_withdrawal_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='image_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
