# Generated by Django 4.2.3 on 2023-11-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_nft_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='nft_image',
        ),
        migrations.RemoveField(
            model_name='mintingpayment',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='verficationfee',
            name='proof',
        ),
        migrations.AddField(
            model_name='marketplace',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mintingpayment',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verficationfee',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
