# Generated by Django 4.2.3 on 2023-11-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_marketplace_nft_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mintingpayment',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mint_payment', to='app.nft'),
        ),
    ]
